Controllers/AdminController.cs
using CSM_NET.Db_context;
using CSM_NET.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CSM_NET.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        
        public ActionResult ComponentList()
        {
            string rootPath = @"Views\Page\Component";

            //TODO: gestire exeption mancanza dir
            List<string> dirs = Directory.GetDirectories(rootPath, "*", SearchOption.AllDirectories).ToList();

            List<string> dirsNames = new List<string>();

            foreach (var item in dirs)
            {
                string name = new DirectoryInfo(item).Name;

                dirsNames.Add(name);
            }


            ViewData["dirs"] = dirsNames;
            
            return View();
        }

        public ActionResult InstallComponent(string name)
        {
            using (CMSContext ctx = new CMSContext())
            {
                ComponentDefinition componentDefinition = new ComponentDefinition(name);

                ctx.componentDefinitions.Add(componentDefinition);
                ctx.SaveChanges();

                return RedirectToAction("ComponentList");
            }
        }

        public ActionResult UninstallComponent(string name)
        {
            using (CMSContext ctx = new CMSContext())
            {
                ComponentDefinition componentDefinition = ctx.componentDefinitions.Find(name);

                if (componentDefinition == null) return NotFound();

                ctx.componentDefinitions.Remove(componentDefinition);
                ctx.SaveChanges();

                return RedirectToAction("ComponentList");
            }
        }


        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Details(int id)
        {
            return View();
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Edit(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PageController.cs
using CSM_NET.Db_context;
using CSM_NET.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CSM_NET.Controllers
{
    public class PageController : Controller
    {
        private readonly ILogger<PageController> _logger;

        public PageController(ILogger<PageController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            using(CMSContext ctx = new CMSContext())
            {
                List<Page> pages = ctx.pages.ToList();

                return View(pages);
            }
        }

        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Page page)
        {
            if (!ModelState.IsValid)
            {
                return View(page);
            }
            
            using(CMSContext ctx = new CMSContext())
            {
                ctx.pages.Add(page);
                ctx.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
           
        }


        public ActionResult Edit(int id)
        {
            using(CMSContext ctx = new CMSContext())
            {
                Page page = ctx.pages.Where(p => p.Id == id).Include(page => page.Components).FirstOrDefault();

                if (page == null) return NotFound();

                return View(page);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSM_NET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CSM_NET.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Page" asp-action="Index">CSM_NET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav"> 
                    <ul class="navbar-nav"> 
                        <li class="nav-item"> 
                            <a class="nav-link" aria-current="page" href="@Url.Action("ComponentList", "Admin")">Admin</a> 
                        </li> <!-- code omitted --> <partial name="_LoginPartial" />
                    </ul> 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CSM_NET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>