Controllers/ComponentController.cs
using CSM_NET.Db_context;
using CSM_NET.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CSM_NET.Controllers
{
    public class ComponentController : Controller
    {
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Select(int Id)
        {

            using(CMSContext ctx = new CMSContext())
            {
                List<ComponentDefinition> componentDefinitionsList = ctx.componentDefinitions.ToList();


                ViewData["pageId"] = Id;

                return View(componentDefinitionsList);
            }

        }

        public ActionResult AddComponent(int pageId, string name)
        {
            using (CMSContext ctx = new CMSContext())
            {
                Page page = ctx.pages.Find(pageId);
                if (page == null) return NotFound();

                ComponentDefinition componentDefinition = ctx.componentDefinitions.Find(name);
                if (componentDefinition == null) return NotFound();

                Component component = new Component()
                {
                    ComponentDefinition = componentDefinition,
                    ComponentDefinitionKey = name,
                    PageId = pageId
                };


                page.Components.Add(component); //errore??


                return RedirectToAction("Select");
            }
        }


        // GET: HomeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string key, int pageId)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PageController.cs
using CSM_NET.Db_context;
using CSM_NET.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CSM_NET.Controllers
{
    public class PageController : Controller
    {
        private readonly ILogger<PageController> _logger;

        public PageController(ILogger<PageController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            using(CMSContext ctx = new CMSContext())
            {
                List<Page> pages = ctx.pages.ToList();

                return View(pages);
            }
        }

        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Page page)
        {
            if (!ModelState.IsValid)
            {
                return View(page);
            }
            
            using(CMSContext ctx = new CMSContext())
            {
                ctx.pages.Add(page);
                ctx.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
           
        }


        public ActionResult Edit(int id)
        {
            using(CMSContext ctx = new CMSContext())
            {
                Page page = ctx.pages.Where(p => p.Id == id).Include(page => page.Components).FirstOrDefault();

                if (page == null) return NotFound();

                return View(page);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Page/Create.cshtml
@model CSM_NET.Models.Page

<h4>Page</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Page/Edit.cshtml
@model CSM_NET.Models.Page

<h4>Page</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <h3>Lista componenti</h3>

            @if (@Model.Components == null || @Model.Components.Count == 0)
            {
                <h4>Non ci sono componenti installati</h4>
            }
            else
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach (Component comp in @Model.Components)
                            {
                                <tr>
                                    <th scope="row">1</th>
                                    <td>@comp.ComponentDefinitionKey</td>
                                    <td>
                                        rimuovi
                                    </td>
                                </tr>
                            }
                    </tbody>
                </table>                
            }
            <a href="@Url.Action("Select", "Component", new { Id = @Model.Id })">Aggiungi un componente</a>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Page/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Page>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="text-center">
    <h1 class="display-4">Pages List</h1>

    @if (Model.Count() == 0)
    {
        <h1 class="display-4">Nessuna pagina in memoria</h1>
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach (Page pag in @Model)
                    {
                        <tr>
                            <th scope="row">1</th>
                            <td>@pag.Name</td>
                            <td>
                                <a asp-controller="Page" asp-action="Edit" asp-route-id="@pag.Id">Edit</a>
                                View/Delete

                            </td>
                        </tr>
                    }
            </tbody>
        </table>

        
    }
    <a href="@Url.Action("Create")">Crea una pagina</a>
</div>